# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['2' 'bottom' 'top' '4.5' 'top' '4.5' '2' 'top' 'top' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [31]:
# Місце для Вашого коду
import numpy as np
print(np.random.choice(9,1))


[5]


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [48]:
# Місце для Вашого коду
import numpy as np
for i in range(6):
    print(np.random.choice(9,4))


[3 8 3 3]
[3 8 0 4]
[4 6 0 4]
[3 1 2 8]
[0 6 6 0]
[4 0 2 8]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 1 4 2 1 4 1 1 0 4]


Згенеруйте одну випадкову цифру.

In [15]:
# Місце для Вашого код

print(np.random.randint(0,1000000000000,1))

[880787163727]


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [46]:
# Місце для Вашого коду
for i in range(5):
    print(np.random.randint(10,99,4))


[61 56 36 32]
[17 75 34 14]
[65 43 78 15]
[44 13 97 51]
[20 39 20 15]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.3369603119037976


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [49]:
# Місце для Вашого коду
for i in range(4):
    print(np.random.sample(3))


[0.92753373 0.69996014 0.11568951]
[0.58898661 0.47911632 0.29689984]
[0.69222054 0.06983492 0.91885981]
[0.24904177 0.87604149 0.4397251 ]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [10]:
a = 3
b = 5

In [27]:
# Місце для Вашого коду

print(2 * np.random.sample(10) + 3)
#print(np.random.randint(a,b,10))


[3.76901408 4.5789732  3.58766767 4.43126416 4.13452242 3.04362888
 4.9887161  3.38186605 3.26110091 3.57702153]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[9 5 3 7 8 1 0 2 6 4]


Перетасуйте матрицю $M$.

In [33]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [51]:
# Місце для Вашого коду
a = np.arange(10)
print('#',a)
np.random.shuffle(a)
print('#',a)
print('#',a.reshape((2,5)))


# [0 1 2 3 4 5 6 7 8 9]
# [6 1 4 7 0 2 3 8 5 9]
# [[6 1 4 7 0]
 [2 3 8 5 9]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [15]:
np.random.seed(42)

In [52]:
print(np.random.randint(10))

3


In [53]:
print(np.random.randint(10))

9


In [57]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [19]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [22]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'T' 'H' 'T' 'T' 'H' 'T' 'H' 'H']


In [23]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

6 heads and 4 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [60]:
# Місце для Вашого коду
tosses = np.random.choice(['A','R'],100)
print(tosses)
obverse = list(tosses).count('A')
reverse = list(tosses).count('R')
print('{} obverse and {} reverse'.format(obverse,reverse))

['R' 'R' 'R' 'R' 'R' 'R' 'R' 'A' 'R' 'A' 'R' 'R' 'A' 'R' 'A' 'R' 'R' 'A'
 'R' 'A' 'R' 'A' 'A' 'R' 'R' 'A' 'R' 'R' 'R' 'A' 'A' 'A' 'A' 'A' 'A' 'A'
 'A' 'A' 'R' 'A' 'R' 'R' 'R' 'A' 'A' 'A' 'A' 'R' 'A' 'A' 'A' 'A' 'A' 'R'
 'A' 'R' 'A' 'R' 'A' 'A' 'R' 'R' 'R' 'A' 'R' 'A' 'A' 'R' 'R' 'A' 'A' 'R'
 'R' 'R' 'A' 'A' 'A' 'A' 'A' 'A' 'R' 'A' 'A' 'A' 'R' 'A' 'A' 'R' 'A' 'A'
 'A' 'A' 'A' 'R' 'R' 'R' 'A' 'A' 'A' 'R']
56 obverse and 44 reverse


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [71]:
# Місце для Вашого коду

tosses = np.random.randint(0,2,100)
print(tosses)
obverse = list(tosses).count(0)
reverse = list(tosses).count(1)
print('{} obverse and {} reverse'.format(obverse,reverse))

[0 0 0 1 0 0 1 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 1
 0 0 0 0 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 0 0 1 0 1 1 0 0 1 1
 0 0 0 0 0 1 1 1 1 0 0 0 1 1 0 0 1 1 0 0 1 0 0 0 1 1]
57 obverse and 43 reverse


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [2]:
# Місце для Вашого коду
import numpy as np

tosses = 1 * np.random.sample(100) + 0
print(tosses)

obverse = list(tosses).count(tosses>0.5)
reverse = list(tosses).count(tosses<0.5)
print('{} obverse and {} reverse'.format(obverse,reverse))


[0.2576728  0.3232795  0.38997631 0.34229071 0.68176818 0.17297059
 0.88803716 0.20323126 0.20041304 0.26336026 0.35574773 0.66284095
 0.57788116 0.86382306 0.94729211 0.97628113 0.88858523 0.41587836
 0.21200331 0.53230884 0.36146794 0.04129697 0.80449312 0.05965209
 0.99104096 0.77659326 0.79457691 0.53102711 0.55796631 0.26477744
 0.77066836 0.13646914 0.00518408 0.81793053 0.85628287 0.42160031
 0.92716613 0.61942354 0.23233042 0.51450901 0.33980595 0.2090529
 0.32063928 0.91858126 0.55077658 0.20508853 0.10607492 0.03359822
 0.7143762  0.12173432 0.85972868 0.52770951 0.35342311 0.66719646
 0.25087978 0.70055513 0.6086521  0.97117577 0.63545512 0.31862555
 0.40964634 0.76008285 0.71609722 0.23080436 0.88652183 0.02758195
 0.26024251 0.34357755 0.98509695 0.35109873 0.17153088 0.06440207
 0.49070732 0.88295151 0.78968927 0.00811234 0.69921944 0.85438587
 0.85914267 0.57681765 0.11279105 0.03416782 0.56141024 0.92637581
 0.70635997 0.88743925 0.92000213 0.92109698 0.52677654 0.16061

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [27]:
# Місце для Вашого коду
n = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]



## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [28]:
# Місце для Вашого коду



### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [29]:
# Місце для Вашого коду



## 5 Колода карт
### 5.1 Реалізація

In [30]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('3', '♣'), ('3', '♠'), ('3', '♡'), ('3', '♢'), ('7', '♣'), ('7', '♠'), ('7', '♡'), ('7', '♢'), ('9', '♣'), ('9', '♠'), ('9', '♡'), ('9', '♢'), ('5', '♣'), ('5', '♠'), ('5', '♡'), ('5', '♢'), ('6', '♣'), ('6', '♠'), ('6', '♡'), ('6', '♢'), ('J', '♣'), ('J', '♠'), ('J', '♡'), ('J', '♢'), ('4', '♣'), ('4', '♠'), ('4', '♡'), ('4', '♢'), ('Q', '♣'), ('Q', '♠'), ('Q', '♡'), ('Q', '♢'), ('8', '♣'), ('8', '♠'), ('8', '♡'), ('8', '♢'), ('10', '♣'), ('10', '♠'), ('10', '♡'), ('10', '♢'), ('1', '♣'), ('1', '♠'), ('1', '♡'), ('1', '♢'), ('2', '♣'), ('2', '♠'), ('2', '♡'), ('2', '♢'), ('K', '♣'), ('K', '♠'), ('K', '♡'), ('K', '♢')]


In [31]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

3♣, 3♠, 3♡, 3♢, 7♣, 7♠, 7♡, 7♢, 9♣, 9♠, 9♡, 9♢, 5♣, 5♠, 5♡, 5♢, 6♣, 6♠, 6♡, 6♢, J♣, J♠, J♡, J♢, 4♣, 4♠, 4♡, 4♢, Q♣, Q♠, Q♡, Q♢, 8♣, 8♠, 8♡, 8♢, 10♣, 10♠, 10♡, 10♢, 1♣, 1♠, 1♡, 1♢, 2♣, 2♠, 2♡, 2♢, K♣, K♠, K♡, K♢


In [32]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♣3, ♣7, ♣9, ♣5, ♣6, ♣J, ♣4, ♣Q, ♣8, ♣10, ♣1, ♣2, ♣K
♠3, ♠7, ♠9, ♠5, ♠6, ♠J, ♠4, ♠Q, ♠8, ♠10, ♠1, ♠2, ♠K
♡3, ♡7, ♡9, ♡5, ♡6, ♡J, ♡4, ♡Q, ♡8, ♡10, ♡1, ♡2, ♡K
♢3, ♢7, ♢9, ♢5, ♢6, ♢J, ♢4, ♢Q, ♢8, ♢10, ♢1, ♢2, ♢K


In [33]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('Q', '♠'), ('10', '♡'), ('3', '♡'), ('2', '♠'), ('2', '♣'), ('10', '♢'), ('J', '♡'), ('1', '♢'), ('9', '♡'), ('3', '♣'), ('6', '♡'), ('Q', '♡'), ('K', '♣'), ('8', '♠'), ('J', '♠'), ('7', '♣'), ('K', '♡'), ('8', '♣'), ('5', '♣'), ('Q', '♢'), ('J', '♣'), ('J', '♢'), ('4', '♡'), ('1', '♡'), ('5', '♡'), ('5', '♢'), ('1', '♣'), ('1', '♠'), ('9', '♠'), ('10', '♣'), ('9', '♢'), ('2', '♢'), ('6', '♠'), ('Q', '♣'), ('10', '♠'), ('7', '♠'), ('2', '♡'), ('K', '♢'), ('8', '♢'), ('6', '♣'), ('K', '♠'), ('8', '♡'), ('7', '♢'), ('7', '♡'), ('4', '♢'), ('6', '♢'), ('3', '♠'), ('4', '♠'), ('9', '♣'), ('5', '♠'), ('4', '♣'), ('3', '♢')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [34]:
# Місце для Вашого коду



### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [35]:
# Місце для Вашого коду



### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [36]:
# Місце для Вашого коду

